version: 2

sources:
  - name: conformed
    database: raw
    schema: conformed

    tables:
      - name: DateDimension
        columns:
          - name: DateKey
            tests:
              - unique

  - name: chinook   
    database: raw
    schema: chinook
    tables:
      - name: Track 
        columns:
          - name: Trackid
            tests:
              - unique
      - name: Artist
        columns:
          - name: Artistid 
            tests:
              - unique        
      - name: Album
        columns:
          - name: Albumid 
            tests:
              - unique   
      - name: genre
        columns:
          - name: genreid 
            tests:
              - unique        
      - name: mediatype
        columns:
          - name: mediatypeid 
            tests:
              - unique 
      - name: invoice
        columns:
          - name: invoiceid 
            tests:
              - unique        
      - name: invoiceline
        columns:
          - name: invoicelineid 
            tests:
              - unique 
      - name: customer
        columns:
          - name: customerid 
            tests:
              - unique 
      - name: customer_track_reviews
        tests:
        - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
              - customerid
              - Trackid
      - name: Playlist
        columns:
          - name: Playlistid 
            tests:
              - unique 
      - name: Playlisttrack