version: 2

sources:
  - name: conformed
    database: raw
    schema: conformed
    tables: []  # This indicates no tables are defined under the 'conformed' source

  - name: chinook
    database: raw
    schema: chinook
    tables:
      - name: Track
        columns:
          - name: TrackId
            tests:
              - unique
      - name: Artist
        columns:
          - name: ArtistId
            tests:
              - unique
      - name: Album
        columns:
          - name: AlbumId
            tests:
              - unique
      - name: invoice
        columns:
          - name: InvoiceId
            tests:
              - unique
      - name: invoiceline
        columns:
          - name: InvoicelineId
            tests:
              - unique
